/**
 * 工地列表
 */
export default {
    TABLE_SHOW_SIZE: 10,
    TABLE_SHOW_SIZE_ARRAY: ['10', '20', '50', '100'],
    TABLE_COLUMNS: [
        {
            title: '序号',
            width: 200,
            key: 'a',
            dataIndex: 'a',
            align: 'center',
            fixed: 'left'
        }, {
            title: '工地编号',
            width: 200,
            key: 'b',
            dataIndex: 'b',
        }, {
            title: '保健编号',
            width: 200,
            key: 'c',
            dataIndex: 'c'
        }, {
            title: '工地项目名称',
            width: 200,
            key: 'd',
            dataIndex: 'd'
        }, {
            title: '工地地址',
            width: 200,
            key: 'e',
            dataIndex: 'e'
        }, {
            title: '合同签定方',
            width: 200,
            key: 'f',
            dataIndex: 'f'
        }, {
            title: '开发商',
            width: 200,
            key: 'g',
            dataIndex: 'g'
        }, {
            title: '施工单位',
            width: 200,
            key: 'h',
            dataIndex: 'h'
        }, {
            title: '占地面积',
            width: 200,
            key: 'i',
            dataIndex: 'i'
        }, {
            title: '施工面积',
            width: 200,
            key: 'j',
            dataIndex: 'j'
        }, {
            title: '联系人',
            width: 200,
            key: 'k',
            dataIndex: 'k'
        }, {
            title: '电话',
            width: 200,
            key: 'l',
            dataIndex: 'l'
        }, {
            title: '安装设备',
            width: 200,
            key: 'm',
            dataIndex: 'm'
        }, {
            title: '控制器编号',
            width: 200,
            key: 'n',
            dataIndex: 'n'
        }, {
            title: '合同签订日期',
            width: 200,
            key: 'o',
            dataIndex: 'o'
        }, {
            title: '合同状态',
            width: 200,
            key: 'p',
            dataIndex: 'p'
        }, {
            title: '数量',
            width: 200,
            key: 'q',
            dataIndex: 'q'
        }, {
            title: '续运维期',
            width: 200,
            key: 'r',
            dataIndex: 'r'
        }, {
            title: '质保/运维期',
            width: 200,
            key: 's',
            dataIndex: 's'
        }, {
            title: '对接负责人',
            width: 200,
            key: 't',
            dataIndex: 't'
        }, {
            title: '联通直传码',
            width: 200,
            key: 'u',
            dataIndex: 'u'
        }, {
            title: '安装时间',
            width: 200,
            key: 'v',
            dataIndex: 'v'
        }, {
            title: '粉尘仪编号',
            width: 200,
            key: 'w',
            dataIndex: 'w'
        }, {
            title: '粉尘仪检测日期',
            width: 200,
            key: 'x',
            dataIndex: 'x'
        }, {
            title: '声级计编号',
            width: 200,
            key: 'y',
            dataIndex: 'y'
        }, {
            title: '声级计检测日期',
            width: 200,
            key: 'z',
            dataIndex: 'z'
        }, {
            title: '采样泵编号',
            width: 200,
            key: 'A',
            dataIndex: 'A'
        }, {
            title: 'SIM卡卡号',
            width: 200,
            key: 'B',
            dataIndex: 'B'
        }, {
            title: '起始日期',
            width: 200,
            key: 'C',
            dataIndex: 'C'
        }, {
            title: '到期日',
            width: 200,
            key: 'D',
            dataIndex: 'D'
        }, {
            title: '上传日期',
            width: 200,
            key: 'E',
            dataIndex: 'E'
        }, {
            title: '租/买',
            width: 200,
            key: 'F',
            dataIndex: 'F'
        }, {
            title: '设备等级',
            width: 200,
            key: 'G',
            dataIndex: 'G'
        }, {
            title: '备注',
            width: 200,
            key: 'H',
            dataIndex: 'H'
        }
    ]
}